GET http://localhost:8000/
###
GET http://localhost:8000/device
###
GET http://localhost:8000/device/ba8p0nfeq8417oihdvvg
###
POST http://localhost:8000/device
Content-Type: application/json

{
    "name" : "pawana",
    "type" : "weather-station"
}
###
GET http://localhost:8000/data
###
GET http://localhost:8000/data/weather-station
###
GET http://localhost:8000/data/solar-simulator
###
POST http://localhost:8000/data?id=ba8p0nfeq8417oihdvvg

{
    "date": "2018-02-26T17:50:42",
    "voltage": "3284",
    "rainfall": "11",
    "direction": "N",
    "speed": "0"
}
###
POST http://localhost:8000/data?id=ba8p11feq8417oihe010

{
    "date": "2018-02-26T17:50:42",
    "voltage" : 12,
    "current" : 1.3
}