GET http://aviana.fadhlika.com/
###
GET http://aviana.fadhlika.com/device
###
GET http://api.aviana.fadhlika.com/device/ba8p0nfeq8417oihdvvg
###
POST http://aviana.fadhlika.com/device
Content-Type: application/json

{
    "name" : "pawana",
    "type" : "weather-station"
}
###
GET http://api.aviana.fadhlika.com/data
###
GET http://aviana.fadhlika.com/data/weather-station
###
GET http://aviana.fadhlika.com/data/solar-simulator
###
POST http://api.aviana.fadhlika.com/data?id=bagavtveq841km2kj600

{
  "date": "2018-03-08T17:53:00",
  "dir": "W",
  "voltage": 3223,
  "speed": 0,
  "rainfall": 0,
  "rssi": -72
}

###
POST http://aviana.fadhlika.com/data?id=ba8p11feq8417oihe010

{
    "date": "2018-02-26T17:50:42",
    "voltage" : 12,
    "current" : 1.3
}