GET http://localhost:8000/
###
GET http://localhost:8000/api/device
###
GET http://localhost:8000/api/device/baefhgneq840jrvpdobg
###
POST http://localhost:8000/device
Content-Type: application/json

{
    "name" : "aviana",
    "type" : "solar-simulator"
}
###
GET http://localhost:8000/data
###
GET http://localhost:8000/data/baaeum3mke00e9u4pdtg/100
###
POST http://localhost:8000/data?id=baaeum3mke00e9u4pdtg

{
    "date": "2018-02-26T19:53:42+07:00",
    "voltage": 3204,
    "rainfall": 11,
    "direction": "N",
    "speed": 1
}
###
POST http://localhost:8000/api/data?id=ba8p11feq8417oihe010

{
    "date": "2018-02-26T17:50:42",
    "voltage" : 12,
    "current" : 1.3
}